
  application:
    name: GHouseApi
  datasource:
    url: jdbc:postgresql://localhost:5432/GHouse
    username: GHouse_admin
    password: AdminGHouse
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
