spring:
  application:
    name: GHouseApi

  datasource:
    url: jdbc:postgresql://localhost:5432/GHouse
    username: GHouse_admin
    password: AdminGHouse
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 60000
      validation-timeout: 5000
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

